# Generated by Django 5.2.7 on 2025-10-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0002_aioperation_documentembedding"),
        ("ai_assistant", "0002_initial"),
    ]

    operations = []
