version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: obcms
      POSTGRES_USER: obcms
      POSTGRES_PASSWORD: obcms_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U obcms"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/src/staticfiles
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://obcms:obcms_dev_password@db:5432/obcms
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - SECRET_KEY=django-insecure-dev-key-change-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    command: >
      sh -c "cd src &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  celery:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://obcms:obcms_dev_password@db:5432/obcms
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - SECRET_KEY=django-insecure-dev-key-change-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    command: >
      sh -c "cd src &&
             celery -A obc_management worker -l info"

  celery-beat:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://obcms:obcms_dev_password@db:5432/obcms
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - SECRET_KEY=django-insecure-dev-key-change-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    command: >
      sh -c "cd src &&
             celery -A obc_management beat -l info"

volumes:
  postgres_data:
  redis_data:
  static_volume: