# Frontend Component Scaffolder Configuration

# Default project paths
project_root: /Users/saidamenmambayao/apps/obcms
templates_dir: src/templates
components_dir: src/templates/components
partials_dir: src/templates/*/partials

# Bangsamoro Color Scheme
colors:
  primary:
    name: ocean
    values:
      50: '#e0f2fe'
      100: '#bae6fd'
      200: '#7dd3fc'
      300: '#38bdf8'
      400: '#0ea5e9'
      500: '#0284c7'
      600: '#0369a1'
      700: '#075985'
      800: '#0c4a6e'
      900: '#082f49'
    
  secondary:
    name: teal
    values:
      50: '#f0fdfa'
      100: '#ccfbf1'
      200: '#99f6e4'
      300: '#5eead4'
      400: '#2dd4bf'
      500: '#14b8a6'
      600: '#0d9488'
      700: '#0f766e'
      800: '#115e59'
      900: '#134e4a'
  
  success:
    name: emerald
    values:
      50: '#ecfdf5'
      100: '#d1fae5'
      200: '#a7f3d0'
      300: '#6ee7b7'
      400: '#34d399'
      500: '#10b981'
      600: '#059669'
      700: '#047857'
      800: '#065f46'
      900: '#064e3b'
  
  warning:
    name: gold
    values:
      50: '#fffbeb'
      100: '#fef3c7'
      200: '#fde68a'
      300: '#fcd34d'
      400: '#fbbf24'
      500: '#f59e0b'
      600: '#d97706'
      700: '#b45309'
      800: '#92400e'
      900: '#78350f'

# Gradient definitions
gradients:
  primary: 'linear-gradient(135deg, #0369a1 0%, #0d9488 50%, #059669 100%)'
  ocean: 'linear-gradient(135deg, #0284c7 0%, #0369a1 100%)'
  ocean_radial: 'radial-gradient(circle at top left, #0ea5e9 0%, #0284c7 100%)'
  teal: 'linear-gradient(135deg, #14b8a6 0%, #0d9488 100%)'
  teal_flow: 'linear-gradient(135deg, #14b8a6 0%, #0d9488 50%, #0f766e 100%)'
  emerald: 'linear-gradient(135deg, #10b981 0%, #059669 100%)'
  emerald_radial: 'radial-gradient(circle at bottom right, #10b981 0%, #059669 100%)'
  gold: 'linear-gradient(135deg, #fbbf24 0%, #f59e0b 50%, #d97706 100%)'
  gold_shine: 'linear-gradient(135deg, #fef3c7 0%, #fbbf24 50%, #f59e0b 100%)'
  sunrise: 'linear-gradient(135deg, #0ea5e9 0%, #14b8a6 33%, #fbbf24 66%, #f59e0b 100%)'
  hero: 'linear-gradient(135deg, #0c4a6e 0%, #075985 50%, #0369a1 100%)'

# Component defaults
component_defaults:
  modal:
    size: md
    closeable: true
    backdrop_dismiss: true
    show_footer: true
  
  data_table:
    show_actions: true
    actions_width: 'w-[8%] min-w-[100px]'
    empty_message: 'No records available.'
    accent: ocean
  
  form:
    method: POST
    show_cancel: true
    submit_color: ocean
    cancel_color: gray
  
  stat_card:
    accent: ocean
    show_link: false
  
  htmx_partial:
    swap: innerHTML
    trigger: load

# Validation rules
validation:
  enforce_color_scheme: true
  require_aria_labels: true
  require_htmx_attributes: false
  check_responsive_classes: true
  max_line_length: 120

# Template engine settings
template_engine:
  type: jinja2
  autoescape: true
  trim_blocks: true
  lstrip_blocks: true

# Generation settings
generation:
  auto_format: true
  add_comments: true
  create_backup: false
  overwrite_existing: false
  verbose: false
