# Generated by Django 5.2.7 on 2025-10-24 14:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetJustification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rationale', models.TextField(blank=True, default='', help_text='Detailed rationale for budget allocation')),
                ('alignment_with_priorities', models.TextField(blank=True, default='', help_text='How this budget aligns with organizational priorities')),
                ('expected_impact', models.TextField(blank=True, default='', help_text='Expected impact and outcomes from this budget allocation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget Justification',
                'verbose_name_plural': 'Budget Justifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('personnel', 'Personnel Services (PS)'), ('operating', 'Maintenance & Other Operating Expenses (MOOE)'), ('capital', 'Capital Outlay (CO)')], default='operating', help_text='Appropriation category (PS/MOOE/CO)', max_length=20)),
                ('sub_category', models.CharField(blank=True, help_text='Optional sub-category (e.g., salaries, training, equipment)', max_length=50)),
                ('description', models.CharField(help_text="Item description (e.g., 'Office Supplies', 'Training Materials')", max_length=255)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit (₱)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.IntegerField(help_text='Number of units', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total cost (auto-calculated: unit_cost × quantity)', max_digits=12)),
                ('justification', models.TextField(blank=True, help_text='Why this line item is required')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or specifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget Line Item',
                'verbose_name_plural': 'Budget Line Items',
                'ordering': ['category', '-total_cost'],
            },
        ),
        migrations.CreateModel(
            name='BudgetProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveIntegerField(help_text='Fiscal year this budget proposal covers', validators=[django.core.validators.MinValueValidator(2024)])),
                ('title', models.CharField(help_text='Budget proposal title', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Overview of budget proposal objectives and scope')),
                ('total_requested_budget', models.DecimalField(decimal_places=2, help_text='Total budget amount requested (₱)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_approved_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Total budget amount approved (₱)', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', help_text='Current review status of the proposal', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Timestamp when the proposal was submitted', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp when the proposal was approved', null=True)),
                ('approval_notes', models.TextField(blank=True, help_text='Approval or rejection notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget Proposal',
                'verbose_name_plural': 'Budget Proposals',
                'ordering': ['-fiscal_year', 'organization'],
            },
        ),
        migrations.CreateModel(
            name='ProgramBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, help_text='Amount requested for this program (₱)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount approved for this program (₱)', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('justification', models.TextField(blank=True, help_text='Justification for the requested amount')),
                ('expected_outcomes', models.TextField(blank=True, help_text='Expected outcomes and beneficiaries')),
                ('priority_rank', models.PositiveIntegerField(default=1, help_text='Priority ranking within the proposal (1 = highest)')),
                ('priority_level', models.CharField(blank=True, editable=False, help_text='Legacy priority field retained for compatibility', max_length=20, null=True)),
                ('expected_outputs', models.TextField(blank=True, editable=False, help_text='Legacy expected outputs field', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program Budget',
                'verbose_name_plural': 'Program Budgets',
                'ordering': ['priority_rank', 'monitoring_entry__title'],
            },
        ),
    ]
