# Generated by Django 5.2.7 on 2025-10-24 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget_preparation', '0001_initial'),
        ('mana', '0001_initial'),
        ('monitoring', '0001_initial'),
        ('organizations', '0001_initial'),
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetjustification',
            name='monitoring_entry_reference',
            field=models.ForeignKey(blank=True, help_text='M&E PPA entry supporting this budget allocation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_justifications', to='monitoring.monitoringentry'),
        ),
        migrations.AddField(
            model_name='budgetjustification',
            name='needs_assessment_reference',
            field=models.ForeignKey(blank=True, help_text='Needs assessment supporting this budget request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_justifications', to='mana.assessment'),
        ),
        migrations.AddField(
            model_name='budgetproposal',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Approving authority', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budget_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetproposal',
            name='organization',
            field=models.ForeignKey(help_text='MOA submitting this budget proposal (BMMS multi-tenant organization)', on_delete=django.db.models.deletion.PROTECT, related_name='budget_proposals', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='budgetproposal',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted this proposal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_budget_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programbudget',
            name='annual_work_plan',
            field=models.ForeignKey(blank=True, help_text='Annual work plan reference for this program', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_budgets', to='planning.annualworkplan'),
        ),
        migrations.AddField(
            model_name='programbudget',
            name='budget_proposal',
            field=models.ForeignKey(help_text='Parent budget proposal', on_delete=django.db.models.deletion.CASCADE, related_name='program_budgets', to='budget_preparation.budgetproposal'),
        ),
        migrations.AddField(
            model_name='programbudget',
            name='monitoring_entry',
            field=models.ForeignKey(blank=True, help_text='Linked monitoring entry (PPA)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_budgets', to='monitoring.monitoringentry'),
        ),
        migrations.AddField(
            model_name='programbudget',
            name='program',
            field=models.ForeignKey(blank=True, editable=False, help_text='Legacy field retained for compatibility', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_budget_allocations', to='planning.workplanobjective'),
        ),
        migrations.AddField(
            model_name='programbudget',
            name='strategic_goal',
            field=models.ForeignKey(blank=True, help_text='Strategic goal supported by this budget', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_budgets', to='planning.strategicgoal'),
        ),
        migrations.AddField(
            model_name='budgetlineitem',
            name='program_budget',
            field=models.ForeignKey(help_text='Parent program budget', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='budget_preparation.programbudget'),
        ),
        migrations.AddField(
            model_name='budgetjustification',
            name='program_budget',
            field=models.ForeignKey(help_text='Program budget being justified', on_delete=django.db.models.deletion.CASCADE, related_name='justifications', to='budget_preparation.programbudget'),
        ),
        migrations.AddIndex(
            model_name='budgetproposal',
            index=models.Index(fields=['organization', 'fiscal_year'], name='budget_prep_organiz_2ee1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetproposal',
            index=models.Index(fields=['status'], name='budget_prep_status_011cb7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetproposal',
            unique_together={('organization', 'fiscal_year')},
        ),
        migrations.AlterUniqueTogether(
            name='programbudget',
            unique_together={('budget_proposal', 'monitoring_entry')},
        ),
        migrations.AddIndex(
            model_name='budgetlineitem',
            index=models.Index(fields=['program_budget', 'category'], name='budget_prep_program_7beec1_idx'),
        ),
    ]
