# Prometheus Configuration for BMMS Phase 8 Full Rollout
# Monitors 44 MOAs infrastructure: Django, PostgreSQL, Redis, Nginx

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'bmms-production'
    environment: 'phase8'

# Alertmanager configuration (optional - uncomment when alerting is set up)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#             - alertmanager:9093

# Load rules once and periodically evaluate them
# rule_files:
#   - /etc/prometheus/rules/*.yml

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Node Exporter (system metrics: CPU, memory, disk)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'system'

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'database'
          role: 'primary'

  # Redis Master metrics
  - job_name: 'redis-master'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'cache'
          role: 'master'

  # Django application servers (custom metrics endpoint)
  # NOTE: Requires django-prometheus or custom /metrics endpoint
  - job_name: 'django-app'
    static_configs:
      - targets:
          - 'web1:8000'
          - 'web2:8000'
          - 'web3:8000'
          - 'web4:8000'
        labels:
          service: 'django'
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx metrics (if nginx-prometheus-exporter is added)
  # - job_name: 'nginx'
  #   static_configs:
  #     - targets: ['nginx-exporter:9113']
  #       labels:
  #         service: 'reverse-proxy'

  # Celery workers (if celery-exporter is added)
  # - job_name: 'celery'
  #   static_configs:
  #     - targets: ['celery-exporter:9540']
  #       labels:
  #         service: 'celery'

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention:
      time: 30d
      size: 10GB
