# Generated by Django 4.2.24 on 2025-09-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mana", "0008_add_administrative_relations"),
    ]

    operations = [
        # Delete the old geographic models from MANA app
        # These models have been moved to the communities app
        migrations.DeleteModel(
            name="SpatialDataPoint",
        ),
        migrations.DeleteModel(
            name="MapVisualization",
        ),
        migrations.DeleteModel(
            name="GeographicDataLayer",
        ),
    ]
