# Generated by Django 5.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mana", "0025_merge_20251025_0031"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="province",
            field=models.ForeignKey(
                blank=True,
                help_text="Province being assessed (for regional/provincial assessments)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessments",
                to="common.province",
            ),
        ),
    ]
