# Generated by Django 5.2.7 on 2025-10-24 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordination', '0001_initial'),
        ('mana', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholderengagement',
            name='related_assessment',
            field=models.ForeignKey(blank=True, help_text='Related assessment (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stakeholder_engagements', to='mana.assessment'),
        ),
        migrations.AddField(
            model_name='engagementfacilitator',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordination.stakeholderengagement'),
        ),
        migrations.AddField(
            model_name='consultationfeedback',
            name='engagement',
            field=models.ForeignKey(help_text='Engagement this feedback relates to', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to='coordination.stakeholderengagement'),
        ),
        migrations.AddField(
            model_name='communication',
            name='related_engagement',
            field=models.ForeignKey(blank=True, help_text='Related stakeholder engagement (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='coordination.stakeholderengagement'),
        ),
        migrations.AddField(
            model_name='stakeholderengagement',
            name='engagement_type',
            field=models.ForeignKey(help_text='Type of engagement activity', on_delete=django.db.models.deletion.PROTECT, to='coordination.stakeholderengagementtype'),
        ),
        migrations.AlterUniqueTogether(
            name='communicationtemplate',
            unique_together={('template_type', 'is_default', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='engagementtracking',
            unique_together={('community', 'period_type', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='intermoapartnership',
            index=models.Index(fields=['lead_moa_code', 'status'], name='coordinatio_lead_mo_b3b346_idx'),
        ),
        migrations.AddIndex(
            model_name='intermoapartnership',
            index=models.Index(fields=['status', 'priority'], name='coordinatio_status_ea6f99_idx'),
        ),
        migrations.AddIndex(
            model_name='intermoapartnership',
            index=models.Index(fields=['start_date', 'end_date'], name='coordinatio_start_d_75720e_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['organization_type', 'partnership_status'], name='coordinatio_organiz_8876a7_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active', 'is_priority'], name='coordinatio_is_acti_4f47d7_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['partnership_level', 'partnership_status'], name='coordinatio_partner_e62ae9_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['region', 'province', 'municipality'], name='coordinatio_region__402c54_idx'),
        ),
        migrations.AddIndex(
            model_name='maofocalperson',
            index=models.Index(fields=['mao', 'is_active'], name='coordinatio_mao_id_c2b615_idx'),
        ),
        migrations.AddIndex(
            model_name='maofocalperson',
            index=models.Index(fields=['user', 'is_active'], name='coordinatio_user_id_f06ede_idx'),
        ),
        migrations.AddIndex(
            model_name='maofocalperson',
            index=models.Index(fields=['role', 'is_active'], name='coordinatio_role_d5cbe0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='maofocalperson',
            unique_together={('mao', 'user', 'role')},
        ),
        migrations.AddIndex(
            model_name='organizationcontact',
            index=models.Index(fields=['organization', 'contact_type'], name='coordinatio_organiz_942310_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationcontact',
            index=models.Index(fields=['is_active', 'is_primary'], name='coordinatio_is_acti_1dbb5d_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationschedule',
            index=models.Index(fields=['organization', 'is_active'], name='coordinatio_organiz_50f366_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationschedule',
            index=models.Index(fields=['next_execution', 'is_active'], name='coordinatio_next_ex_5be056_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationschedule',
            index=models.Index(fields=['assigned_to', 'is_active'], name='coordinatio_assigne_343588_idx'),
        ),
        migrations.AddIndex(
            model_name='partnership',
            index=models.Index(fields=['partnership_type', 'status'], name='coordinatio_partner_e77a00_idx'),
        ),
        migrations.AddIndex(
            model_name='partnership',
            index=models.Index(fields=['status', 'priority'], name='coordinatio_status_caa6e4_idx'),
        ),
        migrations.AddIndex(
            model_name='partnership',
            index=models.Index(fields=['focal_person', 'status'], name='coordinatio_focal_p_03b8c9_idx'),
        ),
        migrations.AddIndex(
            model_name='partnership',
            index=models.Index(fields=['start_date', 'end_date'], name='coordinatio_start_d_94a09a_idx'),
        ),
        migrations.AddIndex(
            model_name='coordinationnote',
            index=models.Index(fields=['note_date'], name='coordinatio_note_da_636500_idx'),
        ),
        migrations.AddIndex(
            model_name='coordinationnote',
            index=models.Index(fields=['work_item'], name='coordinatio_work_it_1de5ea_idx'),
        ),
        migrations.AddIndex(
            model_name='partnershipdocument',
            index=models.Index(fields=['partnership', 'document_type'], name='coordinatio_partner_9e3b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='partnershipdocument',
            index=models.Index(fields=['is_confidential', 'is_public'], name='coordinatio_is_conf_9c0b5d_idx'),
        ),
        migrations.AddIndex(
            model_name='partnershipmilestone',
            index=models.Index(fields=['partnership', 'status'], name='coordinatio_partner_b6fde9_idx'),
        ),
        migrations.AddIndex(
            model_name='partnershipmilestone',
            index=models.Index(fields=['due_date', 'status'], name='coordinatio_due_dat_991763_idx'),
        ),
        migrations.AddIndex(
            model_name='partnershipmilestone',
            index=models.Index(fields=['responsible_organization', 'status'], name='coordinatio_respons_e86aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='partnershipsignatory',
            index=models.Index(fields=['partnership', 'signed'], name='coordinatio_partner_329d87_idx'),
        ),
        migrations.AddIndex(
            model_name='partnershipsignatory',
            index=models.Index(fields=['organization', 'signed'], name='coordinatio_organiz_338283_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partnershipsignatory',
            unique_together={('partnership', 'organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='engagementfacilitator',
            unique_together={('engagement', 'user', 'role')},
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['organization', 'communication_type'], name='coordinatio_organiz_83aec9_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['direction', 'status'], name='coordinatio_directi_c29490_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['communication_date', 'priority'], name='coordinatio_communi_0dd3af_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['requires_follow_up', 'follow_up_date'], name='coordinatio_require_108be2_idx'),
        ),
        migrations.AddIndex(
            model_name='stakeholderengagement',
            index=models.Index(fields=['community', 'status'], name='coordinatio_communi_a6e15b_idx'),
        ),
        migrations.AddIndex(
            model_name='stakeholderengagement',
            index=models.Index(fields=['engagement_type', 'planned_date'], name='coordinatio_engagem_12ed22_idx'),
        ),
        migrations.AddIndex(
            model_name='stakeholderengagement',
            index=models.Index(fields=['status', 'priority'], name='coordinatio_status_f4abc4_idx'),
        ),
        migrations.AddIndex(
            model_name='stakeholderengagement',
            index=models.Index(fields=['is_participatory_budgeting', 'planned_date'], name='coordinatio_is_part_ac77a6_idx'),
        ),
    ]
