# Generated by Django 5.2.7 on 2025-10-05 11:57
"""
Delete legacy Event models in preparation for WorkItem migration.

This migration is part of the StaffTask/Event/ProjectWorkflow → WorkItem consolidation.
Event-related models are deleted here, and EventProxy is created in common.0022.

Migration Sequence:
- common.0020: Create WorkItem model
- common.0021: Delete StaffTask
- coordination.0013: Delete Event (THIS MIGRATION)
- common.0022: Create EventProxy pointing to WorkItem

Note: EventProxy created in common app after Event deleted here.
Proxies point to WorkItem, not the old Event model.

See: docs/refactor/UNIFIED_WORK_HIERARCHY_EVALUATION.md
See: docs/audits/latest/20251025-2347-proxy-model-sequencing-audit.md
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0021_add_model_validation_constraints"),
        ("coordination", "0012_add_model_validation_constraints"),
        ("monitoring", "0017_add_model_validation_constraints"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="EventAttendance",
        ),
        migrations.DeleteModel(
            name="EventDocument",
        ),
        migrations.DeleteModel(
            name="EventParticipant",
        ),
        migrations.DeleteModel(
            name="MAOQuarterlyReport",
        ),
    ]
