# Generated by Django 5.2.7 on 2025-10-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coordination", "0002_initial"),
        (
            "coordination",
            "0017_rename_coordination_intermoapartnership_lead_status_idx_coordinatio_lead_mo_b3b346_idx_and_more",
        ),
    ]

    operations = []
