# Generated by Django 5.2.7 on 2025-10-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0012a_migrate_age_range_data"),
        (
            "communities",
            "0031_remove_municipalitycoverage_communities_munici_org_idx_and_more",
        ),
    ]

    operations = []
