# Generated by Django 5.2.7 on 2025-10-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0002_initial"),
        (
            "communities",
            "0031_remove_municipalitycoverage_communities_munici_org_idx_and_more",
        ),
    ]

    operations = []
