# Generated by Django 5.2.7 on 2025-10-24 14:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_initial'),
        ('coordination', '0002_initial'),
        ('mana', '0001_initial'),
        ('monitoring', '0001_initial'),
        ('policy_tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('unfunded_needs', 'Unfunded High-Priority Needs'), ('overdue_ppa', 'Overdue PPA'), ('pending_mao_report', 'Pending MAO Quarterly Report'), ('budget_ceiling', 'Budget Ceiling Alert'), ('policy_lagging', 'Policy Implementation Lagging'), ('approval_bottleneck', 'Budget Approval Bottleneck'), ('disbursement_delay', 'Disbursement Delay'), ('underspending', 'Underspending Alert'), ('overspending', 'Overspending Warning'), ('workflow_blocked', 'Workflow Blocked'), ('milestone_missed', 'Milestone Missed')], db_index=True, help_text='Type of alert', max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', help_text='Severity level of this alert', max_length=10)),
                ('title', models.CharField(help_text='Short title describing the alert', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the alert and recommended actions')),
                ('alert_data', models.JSONField(default=dict, help_text='Additional structured data related to this alert')),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate to for addressing this alert', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this alert is still active/relevant')),
                ('is_acknowledged', models.BooleanField(default=False, help_text='Whether this alert has been acknowledged by a user')),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When this alert was acknowledged', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes on how this alert was resolved')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this alert should expire (optional)', null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, help_text='User who acknowledged this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('related_mao', models.ForeignKey(blank=True, help_text='Related MAO (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='coordination.organization')),
                ('related_need', models.ForeignKey(blank=True, help_text='Related need (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='mana.need')),
                ('related_policy', models.ForeignKey(blank=True, help_text='Related policy (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='policy_tracking.policyrecommendation')),
                ('related_ppa', models.ForeignKey(blank=True, help_text='Related PPA (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.monitoringentry')),
                ('related_workflow', models.ForeignKey(blank=True, help_text='Related project workflow (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_alerts', to='common.workitem')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type', 'is_active'], name='project_cen_alert_t_fc50e0_idx'), models.Index(fields=['severity', 'is_active', '-created_at'], name='project_cen_severit_331544_idx'), models.Index(fields=['is_active', 'is_acknowledged'], name='project_cen_is_acti_d1b40e_idx')],
            },
        ),
        migrations.CreateModel(
            name='BudgetApprovalStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('draft', 'Draft'), ('technical_review', 'Technical Review'), ('budget_review', 'Budget Review'), ('executive_approval', 'Executive Approval'), ('enacted', 'Enacted')], help_text='Approval stage', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned for Revision')], default='pending', help_text='Current status of this approval stage', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When this stage was approved/rejected', null=True)),
                ('comments', models.TextField(blank=True, help_text='Reviewer comments and feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, help_text='User who approved/rejected this stage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_approvals', to=settings.AUTH_USER_MODEL)),
                ('ppa', models.ForeignKey(help_text='PPA being approved', on_delete=django.db.models.deletion.CASCADE, related_name='approval_stages', to='monitoring.monitoringentry')),
            ],
            options={
                'verbose_name': 'Budget Approval Stage',
                'verbose_name_plural': 'Budget Approval Stages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['ppa', 'stage'], name='project_cen_ppa_id_5e4592_idx'), models.Index(fields=['status', 'stage'], name='project_cen_status_41aadd_idx'), models.Index(fields=['approver', 'approved_at'], name='project_cen_approve_d5a864_idx')],
                'unique_together': {('ppa', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='BudgetCeiling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name for this budget ceiling', max_length=200)),
                ('fiscal_year', models.IntegerField(help_text='Fiscal year this ceiling applies to')),
                ('sector', models.CharField(blank=True, choices=[('economic', 'Economic Development'), ('social', 'Social Development'), ('infrastructure', 'Infrastructure'), ('education', 'Education'), ('health', 'Health'), ('environment', 'Environment & Natural Resources'), ('governance', 'Governance & Institutions'), ('peace', 'Peace & Security'), ('cultural', 'Cultural Development')], help_text='Sector this ceiling applies to (null = all sectors)', max_length=20, null=True)),
                ('funding_source', models.CharField(blank=True, choices=[('gaa', 'General Appropriations Act (GAA)'), ('block_grant', 'Block Grant'), ('lgu', 'Local Government Unit'), ('donor', 'Donor Funding'), ('internal', 'Internal Revenue'), ('others', 'Others')], help_text='Funding source this ceiling applies to (null = all sources)', max_length=20, null=True)),
                ('ceiling_amount', models.DecimalField(decimal_places=2, help_text='Maximum budget allocation allowed', max_digits=12)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount currently allocated (auto-calculated)', max_digits=12)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this ceiling is currently enforced')),
                ('enforcement_level', models.CharField(choices=[('soft', 'Soft Limit (Warning)'), ('hard', 'Hard Limit (Rejection)')], default='hard', help_text='Whether to warn or reject allocations exceeding ceiling', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budget_ceilings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Ceiling',
                'verbose_name_plural': 'Budget Ceilings',
                'ordering': ['-fiscal_year', 'sector', 'funding_source'],
                'indexes': [models.Index(fields=['fiscal_year', 'is_active'], name='project_cen_fiscal__9fd979_idx'), models.Index(fields=['sector', 'fiscal_year'], name='project_cen_sector_9d5716_idx'), models.Index(fields=['funding_source', 'fiscal_year'], name='project_cen_funding_87a4e8_idx')],
                'unique_together': {('fiscal_year', 'sector', 'funding_source')},
            },
        ),
        migrations.CreateModel(
            name='BudgetScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name for this scenario', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of scenario assumptions and goals')),
                ('fiscal_year', models.IntegerField(help_text='Fiscal year this scenario applies to')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_baseline', models.BooleanField(default=False, help_text='Whether this is the baseline scenario (reality/status quo)')),
                ('total_budget_envelope', models.DecimalField(decimal_places=2, help_text='Total budget available in this scenario', max_digits=12)),
                ('allocation_by_sector', models.JSONField(default=dict, help_text='Budget allocation breakdown by sector')),
                ('allocation_by_source', models.JSONField(default=dict, help_text='Budget allocation breakdown by funding source')),
                ('allocation_by_region', models.JSONField(default=dict, help_text='Budget allocation breakdown by region')),
                ('key_assumptions', models.JSONField(default=list, help_text='List of key assumptions underlying this scenario')),
                ('expected_outcomes', models.JSONField(default=list, help_text='Expected outcomes if this scenario is implemented')),
                ('strengths', models.TextField(blank=True, help_text='Strengths of this scenario')),
                ('weaknesses', models.TextField(blank=True, help_text='Weaknesses of this scenario')),
                ('opportunities', models.TextField(blank=True, help_text='Opportunities this scenario enables')),
                ('threats', models.TextField(blank=True, help_text='Threats/risks in this scenario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_scenarios', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_scenarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Scenario',
                'verbose_name_plural': 'Budget Scenarios',
                'ordering': ['-fiscal_year', '-created_at'],
                'indexes': [models.Index(fields=['fiscal_year', 'status'], name='project_cen_fiscal__cb9325_idx'), models.Index(fields=['is_baseline', 'fiscal_year'], name='project_cen_is_base_45636a_idx')],
            },
        ),
    ]
