# Generated by Django 5.2.7 on 2025-10-05 12:09
"""
Delete legacy ProjectWorkflow model and update references to WorkItem.

This migration is part of the StaffTask/Event/ProjectWorkflow → WorkItem consolidation.
ProjectWorkflow is deleted here, and ProjectWorkflowProxy was created in common.0022.

Migration Sequence:
- common.0020: Create WorkItem model
- common.0021: Delete StaffTask
- coordination.0013: Delete Event
- common.0022: Create ProjectWorkflowProxy pointing to WorkItem
- project_central.0004: Delete ProjectWorkflow (THIS MIGRATION)

Note: This migration depends on common.0022, ensuring ProjectWorkflowProxy
exists before ProjectWorkflow is deleted. Alert.related_workflow is updated
to point to WorkItem instead of ProjectWorkflow.

See: docs/refactor/UNIFIED_WORK_HIERARCHY_EVALUATION.md
See: docs/audits/latest/20251025-2347-proxy-model-sequencing-audit.md
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0022_eventproxy_projectworkflowproxy_stafftaskproxy"),
        ("project_central", "0003_budgetapprovalstage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="related_workflow",
            field=models.ForeignKey(
                blank=True,
                help_text="Related project workflow (if applicable)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_alerts",
                to="common.WorkItem",
            ),
        ),
        migrations.DeleteModel(
            name="ProjectWorkflow",
        ),
    ]
