# Generated by Django 5.2.7 on 2025-10-24 14:18

import django.core.validators
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quarter', models.CharField(choices=[('Q1', 'Q1 (Jan–Mar)'), ('Q2', 'Q2 (Apr–Jun)'), ('Q3', 'Q3 (Jul–Sep)'), ('Q4', 'Q4 (Oct–Dec)')], help_text='Quarter identifier (Q1–Q4)', max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Allotment amount (₱)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('released', 'Released'), ('partially_utilized', 'Partially Utilized'), ('fully_utilized', 'Fully Utilized'), ('cancelled', 'Cancelled')], default='pending', help_text='Allotment release status', max_length=25)),
                ('released_at', models.DateField(default=django.utils.timezone.now, help_text='Date the allotment was released')),
                ('reference_number', models.CharField(blank=True, help_text='Optional release reference or document number', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Optional release notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Allotment',
                'verbose_name_plural': 'Allotments',
                'ordering': ['program_budget', 'quarter'],
            },
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount disbursed (₱)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('check', 'Check'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], default='check', max_length=20)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('paid', 'Paid'), ('void', 'Void')], default='processing', max_length=20)),
                ('disbursed_at', models.DateField(default=django.utils.timezone.now, help_text='Date the disbursement was made')),
                ('reference_number', models.CharField(blank=True, help_text='Optional reference (check/voucher number)', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disbursement',
                'verbose_name_plural': 'Disbursements',
                'ordering': ['-disbursed_at'],
            },
        ),
        migrations.CreateModel(
            name='DisbursementLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_center', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disbursement Line Item',
                'verbose_name_plural': 'Disbursement Line Items',
                'db_table': 'budget_execution_disbursement_line_item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Obligated amount (₱)', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payee', models.CharField(blank=True, default='', help_text='Payee or supplier name', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('obligated', 'Obligated'), ('partially_disbursed', 'Partially Disbursed'), ('fully_disbursed', 'Fully Disbursed'), ('cancelled', 'Cancelled')], default='obligated', help_text='Obligation status', max_length=25)),
                ('obligated_at', models.DateField(default=django.utils.timezone.now, help_text='Date the obligation was recorded')),
                ('notes', models.TextField(blank=True, help_text='Additional obligation notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Obligation',
                'verbose_name_plural': 'Obligations',
                'ordering': ['-obligated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Work Item',
                'verbose_name_plural': 'Work Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
