# Generated by Django 5.2.7 on 2025-10-24 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget_execution', '0001_initial'),
        ('budget_preparation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotment',
            name='program_budget',
            field=models.ForeignKey(help_text='Program budget this allotment is released from', on_delete=django.db.models.deletion.CASCADE, related_name='allotments', to='budget_preparation.programbudget'),
        ),
    ]
