# Generated by Django 5.2.7 on 2025-10-24 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget_execution', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='allotment',
            name='released_by',
            field=models.ForeignKey(blank=True, help_text='Budget execution user who released the allotment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allotments_released', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='disbursed_by',
            field=models.ForeignKey(blank=True, help_text='User who processed the disbursement', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disbursements_processed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disbursementlineitem',
            name='disbursement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='budget_execution.disbursement'),
        ),
    ]
