# Generated by Django 5.2.7 on 2025-10-24 14:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget_execution', '0003_initial'),
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementlineitem',
            name='monitoring_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursement_line_items', to='monitoring.monitoringentry'),
        ),
        migrations.AddField(
            model_name='obligation',
            name='allotment',
            field=models.ForeignKey(help_text='Allotment funding this obligation', on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='budget_execution.allotment'),
        ),
        migrations.AddField(
            model_name='obligation',
            name='obligated_by',
            field=models.ForeignKey(blank=True, help_text='User who recorded the obligation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obligations_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='obligation',
            field=models.ForeignKey(help_text='Obligation this disbursement fulfills', on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='budget_execution.obligation'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='monitoring_entry',
            field=models.ForeignKey(help_text='Linked monitoring entry (PPA)', on_delete=django.db.models.deletion.PROTECT, related_name='execution_work_items', to='monitoring.monitoringentry'),
        ),
        migrations.AddField(
            model_name='obligation',
            name='work_item',
            field=models.ForeignKey(blank=True, help_text='Execution work item covered by this obligation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='budget_execution.workitem'),
        ),
        migrations.AddIndex(
            model_name='allotment',
            index=models.Index(fields=['program_budget', 'status'], name='budget_exec_program_1f5da3_idx'),
        ),
        migrations.AddIndex(
            model_name='allotment',
            index=models.Index(fields=['quarter'], name='budget_exec_quarter_d4c8bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='allotment',
            unique_together={('program_budget', 'quarter')},
        ),
        migrations.AddIndex(
            model_name='disbursementlineitem',
            index=models.Index(fields=['disbursement'], name='budget_exec_disburs_9b5b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='disbursementlineitem',
            index=models.Index(fields=['monitoring_entry'], name='budget_exec_monitor_fa2e8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='disbursementlineitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0.01'))), name='disbursement_line_item_positive_amount'),
        ),
        migrations.AddIndex(
            model_name='disbursement',
            index=models.Index(fields=['obligation'], name='budget_exec_obligat_141c46_idx'),
        ),
        migrations.AddIndex(
            model_name='disbursement',
            index=models.Index(fields=['status'], name='budget_exec_status_d00ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['monitoring_entry'], name='budget_exec_monitor_05aa4d_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['status'], name='budget_exec_status_5af77f_idx'),
        ),
        migrations.AddIndex(
            model_name='obligation',
            index=models.Index(fields=['allotment', 'status'], name='budget_exec_allotme_9761f3_idx'),
        ),
        migrations.AddIndex(
            model_name='obligation',
            index=models.Index(fields=['work_item'], name='budget_exec_work_it_086a51_idx'),
        ),
    ]
