# Generated by Django 5.2.7 on 2025-10-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget_execution", "0004_alter_workitem_estimated_cost"),
        ("budget_execution", "0004_initial"),
    ]

    operations = []
