# Generated by Django 5.2.7 on 2025-10-24 14:18

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('common', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('coordination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='moa_organization',
            field=models.ForeignKey(blank=True, help_text='MOA organization this user belongs to (for MOA staff only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moa_staff_users', to='coordination.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(help_text='Type of object being audited', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendarnotification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='calendarnotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendarresourcebooking',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_resource_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendarresourcebooking',
            name='booked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resource_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendarresourcebooking',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='calendarresourcebooking',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='common.calendarresource'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externalcalendarsync',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_calendar_syncs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feature',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this feature is scoped to (null = global feature)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_features', to='coordination.organization'),
        ),
        migrations.AddField(
            model_name='feature',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent feature for hierarchical organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='common.feature'),
        ),
        migrations.AddField(
            model_name='barangay',
            name='municipality',
            field=models.ForeignKey(help_text='Parent municipality', on_delete=django.db.models.deletion.CASCADE, related_name='barangays', to='common.municipality'),
        ),
        migrations.AddField(
            model_name='permission',
            name='feature',
            field=models.ForeignKey(help_text='Feature this permission applies to', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='common.feature'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='province',
            field=models.ForeignKey(help_text='Parent province', on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='common.province'),
        ),
        migrations.AddField(
            model_name='province',
            name='region',
            field=models.ForeignKey(help_text='Parent region', on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='common.region'),
        ),
        migrations.AddField(
            model_name='role',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this role belongs to (null = global role)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='coordination.organization'),
        ),
        migrations.AddField(
            model_name='role',
            name='parent_role',
            field=models.ForeignKey(blank=True, help_text='Parent role for permission inheritance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_roles', to='common.role'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='granted_by',
            field=models.ForeignKey(blank=True, help_text='User who granted this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_role_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(help_text='Permission being granted', on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='common.permission'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(help_text='Role being granted permission', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='common.role'),
        ),
        migrations.AddField(
            model_name='sharedcalendarlink',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_calendar_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffleave',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffleave',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffdevelopmentplan',
            name='staff_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_plans', to='common.staffprofile'),
        ),
        migrations.AddField(
            model_name='performancetarget',
            name='staff_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_targets', to='common.staffprofile'),
        ),
        migrations.AddField(
            model_name='performancetarget',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_targets', to='common.staffteam'),
        ),
        migrations.AddField(
            model_name='staffteammembership',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_team_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffteammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='common.staffteam'),
        ),
        migrations.AddField(
            model_name='staffteammembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='staff_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrollments', to='common.staffprofile'),
        ),
        migrations.AddField(
            model_name='trainingenrollment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='common.trainingprogram'),
        ),
        migrations.AddField(
            model_name='usercalendarpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='granted_by',
            field=models.ForeignKey(blank=True, help_text='User who granted this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_user_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization context for this permission', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_permission_assignments', to='coordination.organization'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permission',
            field=models.ForeignKey(help_text='Permission being granted', on_delete=django.db.models.deletion.CASCADE, related_name='direct_user_assignments', to='common.permission'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='user',
            field=models.ForeignKey(help_text='User being granted permission', on_delete=django.db.models.deletion.CASCADE, related_name='direct_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='User who assigned this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrole',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization context for this role assignment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role_assignments', to='coordination.organization'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(help_text='Role being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='common.role'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(help_text='User being assigned role', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workitem',
            name='assignees',
            field=models.ManyToManyField(blank=True, help_text='Assigned users', related_name='assigned_work_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workitem',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workitem',
            name='implementing_moa',
            field=models.ForeignKey(blank=True, help_text="Implementing MOA organization (denormalized for filtering). Auto-populated from PPA's implementing_moa field.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moa_work_items', to='coordination.organization'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Parent work item (null for top-level)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='common.workitem'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='recurrence_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_work_items', to='common.recurringeventpattern'),
        ),
    ]
