# Generated by Django 5.2.7 on 2025-10-24 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_initial'),
        ('mana', '0001_initial'),
        ('monitoring', '0001_initial'),
        ('policy_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='related_assessment',
            field=models.ForeignKey(blank=True, help_text='Related MANA Assessment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='mana.assessment'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='related_items',
            field=models.ManyToManyField(blank=True, help_text='Related work items (dependencies, references)', related_name='related_to', to='common.workitem'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='related_policy',
            field=models.ForeignKey(blank=True, help_text='Related Policy Recommendation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='policy_tracking.policyrecommendation'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='related_ppa',
            field=models.ForeignKey(blank=True, help_text='Related MOA PPA (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_items', to='monitoring.monitoringentry'),
        ),
        migrations.AddField(
            model_name='workitem',
            name='teams',
            field=models.ManyToManyField(blank=True, help_text='Assigned teams', related_name='work_items', to='common.staffteam'),
        ),
        migrations.CreateModel(
            name='EventProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.workitem',),
        ),
        migrations.CreateModel(
            name='ProjectWorkflowProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Project Workflow',
                'verbose_name_plural': 'Project Workflows',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.workitem',),
        ),
        migrations.CreateModel(
            name='StaffTaskProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Staff Task',
                'verbose_name_plural': 'Staff Tasks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.workitem',),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id', '-timestamp'], name='common_audi_content_fdc9f0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='common_audi_user_id_8e41cd_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='common_audi_action_b7ad6b_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarnotification',
            index=models.Index(fields=['scheduled_for', 'status'], name='common_cale_schedul_574b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarnotification',
            index=models.Index(fields=['recipient', 'scheduled_for'], name='common_cale_recipie_0d23b5_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarresourcebooking',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='common_cale_start_d_a29e4d_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarresourcebooking',
            index=models.Index(fields=['resource', 'status'], name='common_cale_resourc_518ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user', '-created_at'], name='common_chat_user_id_78ce39_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session_id', '-created_at'], name='common_chat_session_1faed9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['topic'], name='common_chat_topic_7cac25_idx'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['module', 'is_active'], name='rbac_featur_module_15e9aa_idx'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['parent', 'sort_order'], name='rbac_featur_parent__868c85_idx'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['organization', 'is_active'], name='rbac_featur_organiz_5375f7_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['feature', 'permission_type', 'is_active'], name='rbac_permis_feature_613c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['codename', 'is_active'], name='rbac_permis_codenam_8e56fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('feature', 'codename')},
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['scope', 'is_active'], name='rbac_role_scope_acbe2d_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['organization', 'is_active'], name='rbac_role_organiz_195702_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['level', 'is_active'], name='rbac_role_level_be9816_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('slug', 'organization')},
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'is_active'], name='rbac_role_p_role_id_4d693d_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['permission', 'is_active'], name='rbac_role_p_permiss_5aad35_idx'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['expires_at'], name='rbac_role_p_expires_5448f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AlterUniqueTogether(
            name='staffteammembership',
            unique_together={('team', 'user')},
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user', 'is_active'], name='rbac_user_p_user_id_3f18cf_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['permission', 'is_active'], name='rbac_user_p_permiss_f78df2_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['organization', 'is_active'], name='rbac_user_p_organiz_72d95d_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['expires_at'], name='rbac_user_p_expires_fca1b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together={('user', 'permission', 'organization')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'is_active'], name='rbac_user_r_user_id_1427b8_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role', 'is_active'], name='rbac_user_r_role_id_b8faa6_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['organization', 'is_active'], name='rbac_user_r_organiz_2e9407_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['expires_at'], name='rbac_user_r_expires_a9e6ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role', 'organization')},
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['work_type', 'status'], name='common_work_work_ty_755571_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['start_date', 'due_date'], name='common_work_start_d_3521a0_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['status', 'priority'], name='common_work_status_25ac42_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['activity_category'], name='wi_activity_category_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['related_ppa'], name='wi_rel_ppa_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['related_assessment'], name='wi_rel_assessment_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['related_policy'], name='wi_rel_policy_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['ppa_category'], name='wi_ppa_category_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['implementing_moa'], name='wi_implementing_moa_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['ppa_category', 'implementing_moa'], name='wi_moa_filter_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tree_id', 'lft', 'rght'], name='wi_tree_traversal_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['parent_id'], name='wi_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['is_calendar_visible', 'start_date', 'due_date'], name='wi_calendar_idx'),
        ),
        migrations.AddIndex(
            model_name='workitem',
            index=models.Index(fields=['tree_id', 'lft'], name='common_workitem_tree_id_lfab60'),
        ),
    ]
