# Generated by Django 5.2.7 on 2025-10-05 11:57
"""
Delete legacy task models in preparation for WorkItem migration.

This migration is part of a larger refactoring that consolidates StaffTask,
ProjectWorkflow, and Event models into a unified WorkItem model.

Migration Sequence:
- 0020: Create WorkItem model
- 0021: Delete StaffTask (THIS MIGRATION)
- 0022: Create StaffTaskProxy pointing to WorkItem
- coordination.0013: Delete Event
- project_central.0004: Delete ProjectWorkflow

Note: Proxy models are created AFTER old models are deleted. This is
intentional - proxies point to WorkItem, not the old models. Reverse
migrations will have limitations due to the architectural nature of this change.

See: docs/refactor/UNIFIED_WORK_HIERARCHY_EVALUATION.md
See: docs/audits/latest/20251025-2347-proxy-model-sequencing-audit.md
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0020_workitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasktemplateitem",
            name="template",
        ),
        migrations.DeleteModel(
            name="StaffTask",
        ),
        migrations.DeleteModel(
            name="TaskTemplate",
        ),
        migrations.DeleteModel(
            name="TaskTemplateItem",
        ),
    ]
