# Generated by Django 5.2.7 on 2025-10-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_initial"),
        ("common", "0046_grant_monitoring_to_oobc_staff"),
    ]

    operations = []
